/**
 * models/Lesson.js
 *
 * The scheduled teaching entity — one occurrence of teaching one piece
 * of curriculum content, assigned to one Teaching Slot (see
 * models/TeachingSlot.js). References curriculum content by id only,
 * never copies it: `curriculumUnitId` and `conceptIds` are resolved
 * live against the Curriculum domain at display time, the same
 * reference-not-copy principle already established for
 * AssessmentSubject.subjectId and Learning Management's Subject ->
 * Curriculum Index link. Curriculum stays the single source of truth;
 * a unit renamed or a concept reworded later needs no Lesson
 * migration.
 *
 * `conceptIds` is an array, not a single `conceptId` — this is a
 * deliberate difference from the earlier draft of this model. Two
 * reasons: it gives the "Concept Builder isn't built yet" fallback
 * (see services/plannerStrategies/balancedStrategy.js) a natural
 * empty-array representation (`conceptIds: []` for a whole-unit
 * placeholder lesson) rather than a special-cased null, and it leaves
 * room for a future strategy to schedule more than one concept per
 * lesson without another model change.
 *
 * `teachingSlotId` references models/TeachingSlot.js's own generated
 * id — not the slot's date/period directly, so a Lesson's origin slot
 * stays traceable even if slot data is later regenerated or replaced
 * by a different source (manual entry today, a real Timetable
 * eventually).
 *
 * `estimatedMinutes` is populated from the originating Teaching Slot's
 * own `duration` at generation time — what the lesson was scheduled
 * to take. `actualMinutes` stays null until a teacher records it after
 * the fact; nothing in this milestone sets it.
 *
 * `status` — 'planned' | 'taught' | 'skipped' | 'rescheduled'. Nothing
 * in this milestone changes it after creation (no calendar UI, no
 * teacher-facing status controls yet) — see
 * services/plannerService.js's recordLessonStatusChange() for the one
 * piece of status-transition logic this milestone does include, ready
 * for a future UI to call.
 *
 * `planningCycleId` — nullable. A Lesson generated by the Planner
 * engine's balanced strategy always has one; a Lesson created directly
 * by attaching a lesson plan to a Timetable period (see
 * services/timetableLessonService.js) does not belong to any
 * PlanningCycle at all, and null is the correct, real value for it —
 * never a fabricated placeholder id.
 *
 * `executedConceptIds` — subset of `conceptIds`: which of the PLANNED
 * concepts were actually taught in this specific occurrence (see
 * services/timetableLessonService.js's markConceptsExecuted(), which
 * is the only place this is ever set, and enforces the subset
 * invariant). Deliberately separate from the classroom-level
 * `LearningConcept.status` ('taught'/'not_taught') — that flag is
 * shared across the whole syllabus tree and flips once, the first time
 * a concept is genuinely executed anywhere; `executedConceptIds` is
 * this one Lesson's own record of what happened in this one occurrence,
 * which is what "only executed concepts are eligible for student
 * feedback" (per this occurrence) actually needs. A planned concept
 * NOT in `executedConceptIds` was either not yet taught, or — see
 * `carriedForwardConceptIds` below — moved to a different occurrence
 * instead.
 */

import { generateId } from '../utils/idGenerator.js';

export function createLesson({
  id,
  planningCycleId = null,
  classroomId,
  date,
  teachingSlotId,
  curriculumUnitId,
  conceptIds = [],
  executedConceptIds = [],
  carriedForwardConceptIds = [],
  conceptProvenance = {},
  // Pre-existing latent bug, fixed here: with no default, this stayed
  // `undefined` for any Lesson created outside services/plannerStrategies/
  // balancedStrategy.js (the only caller that ever explicitly supplies
  // it) — and Firestore's setDoc() rejects any field whose value is
  // `undefined` outright. Every other genuinely-optional field on this
  // model already defaults to `null` for exactly this reason
  // (planningCycleId, estimatedMinutes, actualMinutes below); this one
  // was simply missed until services/timetableLessonService.js's
  // attachLessonPlan() became the first caller that doesn't supply it.
  sequenceIndex = null,
  estimatedMinutes = null,
  actualMinutes = null,
  status = 'planned',
  teacherReflection = null,
  feedbackSharedAt = null,
} = {}) {
  return {
    id: id || generateId(),
    planningCycleId,
    classroomId,
    date,
    teachingSlotId,
    curriculumUnitId,
    conceptIds,
    executedConceptIds,
    // `carriedForwardConceptIds` — subset of conceptIds: planned here,
    // but moved to a different (future) occurrence instead of being
    // taught here. Stays listed in conceptIds (so this Lesson's own
    // Planned Concepts list keeps showing it, per the approved
    // reference) — never removed, never re-added elsewhere as a new
    // id. See services/carryForwardService.js for the one place this
    // is ever set.
    carriedForwardConceptIds,
    // `conceptProvenance` — { [conceptId]: { fromLessonId,
    // fromTeachingSlotId, carriedAt } }, present ONLY for concepts that
    // arrived on THIS Lesson via carry-forward from a different one.
    // Together with the source Lesson's own carriedForwardConceptIds
    // entry, this is what makes "D was originally planned for Tuesday,
    // carried forward, then taught on Thursday" fully reconstructable
    // later without inspecting anything beyond these two Lessons — see
    // services/carryForwardService.js.
    conceptProvenance,
    sequenceIndex,
    estimatedMinutes,
    actualMinutes,
    status,
    // `teacherReflection` — free text, nullable. The Period Detail
    // panel's own "Teacher Reflection" field (see the approved
    // reference) — a private note against this one occurrence, not
    // shown to students.
    teacherReflection,
    // `feedbackSharedAt` — ISO string, nullable. Set once, the moment
    // "Share feedback with students" is tapped (see
    // services/timetableLessonService.js's shareFeedbackWithStudents())
    // — not the same moment as executedConceptIds being populated: a
    // teacher may mark concepts executed and still want to add a
    // reflection or double check before actually sharing. The concept
    // list students actually see is always resolved fresh from
    // executedConceptIds at read time (see getFeedbackEligibleConceptIds()
    // below) — this field only gates *whether* that's happened yet,
    // never a separate copy of *which* concepts.
    feedbackSharedAt,
  };
}

/**
 * Pure validation: which of `executedConceptIds` are NOT actually in
 * this Lesson's own `conceptIds` — an empty array means the whole set
 * is valid. Kept here, in this dependency-free model file, rather than
 * inline in services/timetableLessonService.js (which transitively
 * imports the real Firestore SDK from a remote https:// URL that
 * Node's own test runner cannot resolve at all) specifically so this
 * one invariant — "executedConceptIds must be a subset of conceptIds"
 * — stays directly unit-testable.
 */
export function findInvalidExecutedConceptIds(lesson, executedConceptIds) {
  return executedConceptIds.filter((conceptId) => !lesson.conceptIds.includes(conceptId));
}

/** Only executed concepts are eligible for student feedback — see this file's own executedConceptIds doc comment for why this is scoped per-occurrence, not the classroom-wide LearningConcept.status. */
export function getFeedbackEligibleConceptIds(lesson) {
  return [...lesson.executedConceptIds];
}

/**
 * Reassigns `lesson` to a different curriculumUnitId — a pure,
 * dependency-free mutation (same rationale as findInvalidExecutedConceptIds()
 * above: directly unit-testable without pulling in
 * services/plannerRepository.js's real Firestore import). Kept here,
 * not inline in ui/views/TimetableView.js's own openEditLessonUnitFlow(),
 * so this one invariant — "a concept id from the old unit is meaningless
 * against the new one, so every concept-related field resets rather
 * than silently carrying stale ids across" — stays covered by a real
 * test rather than only ever exercised by hand in a browser.
 *
 * Every concept-related field resets, not just conceptIds: executedConceptIds/
 * carriedForwardConceptIds/conceptProvenance would otherwise keep
 * referencing concept ids that no longer belong to this lesson's own
 * unit, and feedbackSharedAt would otherwise still claim feedback was
 * shared for a set of concepts that no longer applies.
 *
 * Caller's responsibility (not this function's): deciding whether to
 * warn/confirm before calling this when the lesson already has
 * concepts, and persisting the result afterward — this only ever
 * mutates the in-memory `lesson` object handed to it.
 */
export function resetLessonForUnitChange(lesson, newUnitId) {
  lesson.curriculumUnitId = newUnitId;
  lesson.conceptIds = [];
  lesson.executedConceptIds = [];
  lesson.carriedForwardConceptIds = [];
  lesson.conceptProvenance = {};
  lesson.feedbackSharedAt = null;
  return lesson;
}

/**
 * Moves one planned concept from `sourceLesson` to `targetLesson` —
 * a pure, dependency-free mutation (no Firestore, no id generation)
 * kept in this model file for the same reason findInvalidExecutedConceptIds()
 * above is: so this exact invariant stays directly unit-testable
 * without pulling in services/plannerRepository.js's real Firestore
 * import. The orchestration around it (finding/creating the target
 * Lesson, persisting both afterward) lives in
 * services/carryForwardService.js.
 *
 * Never clones the LearningConcept and never generates a new id —
 * `conceptId` is reused verbatim on both ends. It STAYS in
 * sourceLesson.conceptIds (so that lesson's own Planned Concepts list
 * keeps listing it, matching the approved reference) but is recorded
 * in sourceLesson.carriedForwardConceptIds so it's never mistaken for
 * "still awaiting execution here." It's appended to
 * targetLesson.conceptIds, with a conceptProvenance entry recording
 * exactly where it came from and when — together, these two Lessons
 * fully reconstruct "originally planned on Tuesday, carried forward,
 * (eventually) taught on Thursday" with nothing else to inspect.
 *
 * Throws rather than silently doing something ambiguous when the
 * concept isn't actually eligible to be carried: not planned on the
 * source at all, already executed there (nothing left to carry), already
 * carried forward once before (carrying the same concept twice would
 * leave two different target lessons both claiming it), or already
 * present on the target (would silently duplicate it in conceptIds).
 */
export function carryForwardConcept({ sourceLesson, targetLesson, conceptId, sourceTeachingSlotId, carriedAt }) {
  if (!sourceLesson.conceptIds.includes(conceptId)) {
    throw new Error(`Concept ${conceptId} is not planned on the source lesson`);
  }
  if (sourceLesson.executedConceptIds.includes(conceptId)) {
    throw new Error(`Concept ${conceptId} was already executed — nothing to carry forward`);
  }
  if (sourceLesson.carriedForwardConceptIds.includes(conceptId)) {
    throw new Error(`Concept ${conceptId} has already been carried forward`);
  }
  if (targetLesson.conceptIds.includes(conceptId)) {
    throw new Error(`Concept ${conceptId} is already planned on the target lesson`);
  }

  sourceLesson.carriedForwardConceptIds = [...sourceLesson.carriedForwardConceptIds, conceptId];
  targetLesson.conceptIds = [...targetLesson.conceptIds, conceptId];
  targetLesson.conceptProvenance = {
    ...targetLesson.conceptProvenance,
    [conceptId]: { fromLessonId: sourceLesson.id, fromTeachingSlotId: sourceTeachingSlotId, carriedAt },
  };

  return { sourceLesson, targetLesson };
}
