/**
 * services/chapterPlanProgressService.js
 *
 * Read-only derived progress for one ChapterPlan — "how much of this
 * chapter has actually been planned/taught week-to-week" — computed
 * live from Lesson documents, never stored anywhere. Per the approved
 * connected-planning architecture: a ChapterPlan does not own Lessons,
 * so it cannot answer this question from its own fields; the answer
 * only ever exists as a query over Lesson at read time.
 *
 * The join key is `classroomId` + `curriculumUnitId` — NEVER
 * `linkedCurriculumUnitId`. `curriculumUnitId` (a LearningUnit.id) is
 * generated fresh per classroom, so filtering by it (scoped to this
 * plan's own classroomId) can never pull in a different Fellow's own
 * Lessons for the "same" chapter, even when both classrooms link the
 * same shared Curriculum Index unit. `linkedCurriculumUnitId` stays
 * reserved for cross-Fellow discovery (Spark/Resource browsing) only —
 * using it here would silently aggregate other classrooms' Lessons
 * into this plan's own progress numbers.
 *
 * `lessonsPlanned` deliberately reuses
 * services/weeklyPlanValidationService.js's own
 * hasMeaningfulWeeklyPlanContent() verbatim — the SAME "has this period
 * actually been planned" definition the Weekly Plan dashboard already
 * uses to distinguish "Draft" from "Not started" — never a second,
 * independently-invented threshold. A Lesson document merely EXISTING
 * (e.g. a placeholder generated by the Planner engine with a
 * curriculumUnitId but no real content yet) does not count; nor does
 * `lessonsWithDetailedPlan` overlap with this — that is its own,
 * stricter count (`lesson.lessonPlanId` set), kept separate rather than
 * folded into "planned" since a detailed LessonPlan is a distinct,
 * optional elaboration on top of an already-planned Lesson (see
 * models/LessonPlan.js's own header comment).
 *
 * `conceptsAddressed` is the union of each planned Lesson's own
 * `executedConceptIds` — concepts actually TAUGHT, not merely planned —
 * matching models/Lesson.js's own getFeedbackEligibleConceptIds()
 * convention for "what really happened" vs. `conceptIds` ("what was
 * planned"). `conceptsIntended` is `chapterPlan.conceptIds` verbatim.
 * The two are returned side by side and are NEVER reconciled into one
 * list — one is authored intent, the other is derived reality; per
 * explicit product direction, neither should silently overwrite the
 * other.
 *
 * Pure and Firestore-free, same "stays directly unit-testable"
 * convention as weeklyPlanGridService.js/chapterPlanReviewIndexService.js:
 * `lessons` is whatever the caller already fetched (e.g.
 * services/plannerRepository.js's getLessonsForUnit()) — this file
 * never queries Firestore itself, and never writes its return value
 * back onto the ChapterPlan document.
 */

import { hasMeaningfulWeeklyPlanContent } from './weeklyPlanValidationService.js';
import { getMondayStartOfWeek } from '../utils/dateHelpers.js';
import { parsePeriodNumberFromTeachingSlotId } from './timetableService.js';

function belongsToChapterPlan(lesson, chapterPlan) {
  return lesson.classroomId === chapterPlan.classroomId && lesson.curriculumUnitId === chapterPlan.curriculumUnitId;
}

/**
 * `{ lessonsPlanned, lessonsWithDetailedPlan, weeksSpanned,
 * conceptsAddressed, conceptsIntended, lastPlannedDate }` — see this
 * file's own header comment for what each one means and why. `lessons`
 * may be any array of Lesson documents (e.g. every Lesson in the
 * classroom) — this function does its own classroomId+curriculumUnitId
 * filtering, so a caller never has to get that join exactly right
 * itself.
 */
export function getChapterPlanProgress(lessons, chapterPlan) {
  const matchingLessons = (lessons || []).filter((lesson) => belongsToChapterPlan(lesson, chapterPlan));
  const plannedLessons = matchingLessons.filter((lesson) => hasMeaningfulWeeklyPlanContent(lesson));

  const weekStartDates = new Set(plannedLessons.filter((lesson) => lesson.date).map((lesson) => getMondayStartOfWeek(lesson.date)));

  const conceptsAddressed = new Set();
  plannedLessons.forEach((lesson) => {
    (lesson.executedConceptIds || []).forEach((conceptId) => conceptsAddressed.add(conceptId));
  });

  const lastPlannedDate = plannedLessons.reduce((latest, lesson) => {
    if (!lesson.date) return latest;
    return !latest || lesson.date > latest ? lesson.date : latest;
  }, null);

  return {
    lessonsPlanned: plannedLessons.length,
    lessonsWithDetailedPlan: matchingLessons.filter((lesson) => Boolean(lesson.lessonPlanId)).length,
    weeksSpanned: weekStartDates.size,
    conceptsAddressed: [...conceptsAddressed],
    conceptsIntended: [...(chapterPlan.conceptIds || [])],
    lastPlannedDate,
  };
}

/**
 * The "Weeks" lens's own list — every week this chapter has a real
 * footprint in, one entry per distinct Monday-start week among this
 * chapter's own planned Lessons (same classroomId+curriculumUnitId join,
 * same hasMeaningfulWeeklyPlanContent() "planned" definition as
 * getChapterPlanProgress() above — never a second, separately-invented
 * notion of "planned"). `{ weekStartDate, lessonCount }[]`, sorted
 * ascending by date. This is deliberately NOT a reconstruction of the
 * week itself (no periods, no subjects, no times) — per the approved
 * architecture, the actual week is always rendered by the EXISTING
 * Weekly Plan grid (services/weeklyPlanGridService.js's own
 * buildWeeklyPlanGrid(), as already rendered by
 * ui/views/WeeklyPlanReviewView.js); this is only the index of WHICH
 * weeks to offer as a jump-off point, not a copy of what's in them.
 */
export function getChapterPlanWeeks(lessons, chapterPlan) {
  const matchingLessons = (lessons || []).filter((lesson) => belongsToChapterPlan(lesson, chapterPlan));
  const plannedLessons = matchingLessons.filter((lesson) => hasMeaningfulWeeklyPlanContent(lesson) && lesson.date);

  const countByWeekStartDate = new Map();
  plannedLessons.forEach((lesson) => {
    const weekStartDate = getMondayStartOfWeek(lesson.date);
    countByWeekStartDate.set(weekStartDate, (countByWeekStartDate.get(weekStartDate) || 0) + 1);
  });

  return [...countByWeekStartDate.entries()]
    .map(([weekStartDate, lessonCount]) => ({ weekStartDate, lessonCount }))
    .sort((a, b) => (a.weekStartDate < b.weekStartDate ? -1 : a.weekStartDate > b.weekStartDate ? 1 : 0));
}

/**
 * The "Lessons" lens's own list — every real Lesson document belonging
 * to this Chapter (same classroomId+curriculumUnitId join as
 * getChapterPlanProgress()/getChapterPlanWeeks() above — never
 * linkedCurriculumUnitId), returned chronologically (by date, then by
 * period number for same-day Lessons). Deliberately NOT filtered by
 * hasMeaningfulWeeklyPlanContent() the way the other two functions in
 * this file are — the Lessons tab's own job is to show every real
 * occurrence tied to this chapter so a Fellow can see and open even a
 * barely-touched one, not to pre-judge which ones count as "planned."
 *
 * Returns the raw Lesson documents, unmodified — whether a detailed
 * LessonPlan exists is already a plain field on each one
 * (`lesson.lessonPlanId`), and concept titles are resolved by the
 * caller via services/timetableDisplayService.js's own
 * resolveLessonConcepts(), exactly as ui/views/WeeklyPlanReviewView.js
 * already does — this function never duplicates that resolution.
 */
export function getChapterPlanLessons(lessons, chapterPlan) {
  return (lessons || [])
    .filter((lesson) => belongsToChapterPlan(lesson, chapterPlan))
    .slice()
    .sort((a, b) => {
      if (a.date !== b.date) return a.date < b.date ? -1 : 1;
      const periodA = parsePeriodNumberFromTeachingSlotId(a.teachingSlotId) ?? 0;
      const periodB = parsePeriodNumberFromTeachingSlotId(b.teachingSlotId) ?? 0;
      return periodA - periodB;
    });
}
