/**
 * services/chapterPlanProgressService.js
 *
 * Read-only derived progress for one ChapterPlan — "how much of this
 * chapter has actually been planned/taught week-to-week" — computed
 * live from Lesson documents, never stored anywhere. Per the approved
 * connected-planning architecture: a ChapterPlan does not own Lessons,
 * so it cannot answer this question from its own fields; the answer
 * only ever exists as a query over Lesson at read time.
 *
 * The join key is `classroomId` + `curriculumUnitId` — NEVER
 * `linkedCurriculumUnitId`. `curriculumUnitId` (a LearningUnit.id) is
 * generated fresh per classroom, so filtering by it (scoped to this
 * plan's own classroomId) can never pull in a different Fellow's own
 * Lessons for the "same" chapter, even when both classrooms link the
 * same shared Curriculum Index unit. `linkedCurriculumUnitId` stays
 * reserved for cross-Fellow discovery (Spark/Resource browsing) only —
 * using it here would silently aggregate other classrooms' Lessons
 * into this plan's own progress numbers.
 *
 * `lessonsPlanned` deliberately reuses
 * services/weeklyPlanValidationService.js's own
 * hasMeaningfulWeeklyPlanContent() verbatim — the SAME "has this period
 * actually been planned" definition the Weekly Plan dashboard already
 * uses to distinguish "Draft" from "Not started" — never a second,
 * independently-invented threshold. A Lesson document merely EXISTING
 * (e.g. a placeholder generated by the Planner engine with a
 * curriculumUnitId but no real content yet) does not count; nor does
 * `lessonsWithDetailedPlan` overlap with this — that is its own,
 * stricter count (`lesson.lessonPlanId` set), kept separate rather than
 * folded into "planned" since a detailed LessonPlan is a distinct,
 * optional elaboration on top of an already-planned Lesson (see
 * models/LessonPlan.js's own header comment).
 *
 * `conceptsAddressed` is the union of each planned Lesson's own
 * `executedConceptIds` — concepts actually TAUGHT, not merely planned —
 * matching models/Lesson.js's own getFeedbackEligibleConceptIds()
 * convention for "what really happened" vs. `conceptIds` ("what was
 * planned"). `conceptsIntended` is `chapterPlan.conceptIds` verbatim.
 * The two are returned side by side and are NEVER reconciled into one
 * list — one is authored intent, the other is derived reality; per
 * explicit product direction, neither should silently overwrite the
 * other.
 *
 * Pure and Firestore-free, same "stays directly unit-testable"
 * convention as weeklyPlanGridService.js/chapterPlanReviewIndexService.js:
 * `lessons` is whatever the caller already fetched (e.g.
 * services/plannerRepository.js's getLessonsForUnit()) — this file
 * never queries Firestore itself, and never writes its return value
 * back onto the ChapterPlan document.
 */

import { hasMeaningfulWeeklyPlanContent } from './weeklyPlanValidationService.js';
import { getMondayStartOfWeek } from '../utils/dateHelpers.js';

function belongsToChapterPlan(lesson, chapterPlan) {
  return lesson.classroomId === chapterPlan.classroomId && lesson.curriculumUnitId === chapterPlan.curriculumUnitId;
}

/**
 * `{ lessonsPlanned, lessonsWithDetailedPlan, weeksSpanned,
 * conceptsAddressed, conceptsIntended, lastPlannedDate }` — see this
 * file's own header comment for what each one means and why. `lessons`
 * may be any array of Lesson documents (e.g. every Lesson in the
 * classroom) — this function does its own classroomId+curriculumUnitId
 * filtering, so a caller never has to get that join exactly right
 * itself.
 */
export function getChapterPlanProgress(lessons, chapterPlan) {
  const matchingLessons = (lessons || []).filter((lesson) => belongsToChapterPlan(lesson, chapterPlan));
  const plannedLessons = matchingLessons.filter((lesson) => hasMeaningfulWeeklyPlanContent(lesson));

  const weekStartDates = new Set(plannedLessons.filter((lesson) => lesson.date).map((lesson) => getMondayStartOfWeek(lesson.date)));

  const conceptsAddressed = new Set();
  plannedLessons.forEach((lesson) => {
    (lesson.executedConceptIds || []).forEach((conceptId) => conceptsAddressed.add(conceptId));
  });

  const lastPlannedDate = plannedLessons.reduce((latest, lesson) => {
    if (!lesson.date) return latest;
    return !latest || lesson.date > latest ? lesson.date : latest;
  }, null);

  return {
    lessonsPlanned: plannedLessons.length,
    lessonsWithDetailedPlan: matchingLessons.filter((lesson) => Boolean(lesson.lessonPlanId)).length,
    weeksSpanned: weekStartDates.size,
    conceptsAddressed: [...conceptsAddressed],
    conceptsIntended: [...(chapterPlan.conceptIds || [])],
    lastPlannedDate,
  };
}
